---
title: "Untitled"
author: "JJayes"
date: '2022-04-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Reading in the data

```{r}
library(tidyverse)
df <- readr::read_csv("https://www.metoffice.gov.uk/hadobs/hadcrut5/data/current/analysis/diagnostics/HadCRUT.5.0.1.0.analysis.summary_series.global.monthly.csv")

df
```

```{r}
df %>% colnames()
```


```{r}
df <- df %>% 
  janitor::clean_names()

df
```


### EDA

```{r}
df %>% skimr::skim()
```

```{r}
df %>% 
  ggplot(aes(x = time, y = anomaly_deg_c)) +
  geom_point()
```

```{r}
df %>% 
  select(time)
```

```{r}
df <- df %>% 
  mutate(time = lubridate::ymd(paste0(time, "-01")))
```

```{r}
df %>% 
  ggplot(aes(x = time, y = anomaly_deg_c)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, lty = 2)
```


### Recreating the figure

```{r}
df %>% 
  ggplot(aes(x = time, y = 1, fill = anomaly_deg_c)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                       midpoint = 0) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(x = "Year",
       y = NULL,
       caption = "Inspred by Ed Hawkins\nData from the Met Office")
```

```{r}
df <- df %>% 
  mutate(year = lubridate::year(time)) %>% 
  group_by(year) %>% 
  mutate(across(anomaly_deg_c:upper_confidence_limit_97_5_percent, mean)) %>% 
  ungroup() %>% 
  distinct(year, .keep_all = T)
```

```{r}
df %>% 
    ggplot(aes(x = time, y = 1, fill = anomaly_deg_c)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                       midpoint = 0) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(x = "Year",
       y = NULL,
       caption = "Inspred by Ed Hawkins\nData from the Met Office")
```


### Interactivity

```{r}
library(ggiraph)

g <- df %>%
  mutate(tooltip = str_c("Deviation from base period in ", year, "\n", round(anomaly_deg_c, 2), " c")) %>% 
  ggplot(aes(x = time, y = 1, fill = anomaly_deg_c, tooltip = tooltip)) +
  geom_tile_interactive() +
  scale_fill_gradient2(
    low = "blue", high = "red", mid = "white",
    midpoint = 0
  ) +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank()
  ) +
  labs(
    x = "Year",
    y = NULL,
    caption = "Inspred by Ed Hawkins\nData from the Met Office"
  )

ggiraph(ggobj = g)
```




