project:
  type: website
  output-dir: docs

website:
  title: "Kathy's coding club"
  fav-icon: "images/favicon.ico"
  navbar:
    background: light
    logo: images/favicon.ico
    left:
      - href: index.qmd
        text: Screencasts
    right: 
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/j-jayes/screencasts
  repo-url: "https://github.com/j-jayes/screencasts"
  page-footer: '© 2022'

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true

editor: source

